// Reads templates/*.md from the repo root and writes a TypeScript
// constant per supported template into lib/templates/{slug}/standard-terms.ts.
// Strips Common Paper's <span class="*_link"> cross-reference tags
// (rendered in the generated TS as bold field markers) and other
// presentational <span> wrappers, and normalizes curly quotes.
//
// Run via `npm run generate-terms` (also wired to predev/prebuild).

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..");
const templatesDir = join(repoRoot, "templates");
const outBase = join(repoRoot, "frontend", "lib", "templates");

// One entry per supported template. Add a row when promoting a template
// from "coming soon" to fully supported on the picker.
const SUPPORTED = [
  { slug: "mutual-nda", source: "Mutual-NDA.md" },
  { slug: "ai-addendum", source: "AI-Addendum.md" },
];

function transform(md) {
  let s = md;
  // <span class="*_link">X</span> -> **X** (cover-page field markers)
  s = s.replace(/<span class="[^"]*_link"[^>]*>([\s\S]*?)<\/span>/g, "**$1**");
  // Other presentational spans: drop the wrapper, keep the content.
  s = s.replace(/<span\b[^>]*>([\s\S]*?)<\/span>/g, "$1");
  // Curly -> straight quotes for consistency with existing tests / preview.
  s = s.replace(/[“”]/g, '"').replace(/[‘’]/g, "'");
  return s;
}

function escapeBackticks(s) {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

for (const { slug, source } of SUPPORTED) {
  const md = readFileSync(join(templatesDir, source), "utf-8");
  const transformed = transform(md);
  const outDir = join(outBase, slug);
  mkdirSync(outDir, { recursive: true });
  const outFile = join(outDir, "standard-terms.ts");
  const body =
    "// AUTO-GENERATED by scripts/generate-terms.mjs from templates/" +
    source +
    ". Do not edit.\n" +
    "export const STANDARD_TERMS_MARKDOWN = `" +
    escapeBackticks(transformed) +
    "`;\n";
  writeFileSync(outFile, body, "utf-8");
  console.log(`generated ${outFile}`);
}
