/** Single source of truth for the legal disclaimer text. Used by the
 * footer (every page) and the in-app draft banner. */
export const LEGAL_DISCLAIMER =
  "Documents generated by Prelegal are drafts intended as starting points only. They are not legal advice and must be reviewed by a qualified attorney before signing or relying on them.";
